spring.application.name=MDDBackEnd
spring.mvc.dispatch-options-request=true
server.port=3001

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.username=${DB_USERNAME}
spring.datasource.hikari.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

spring.main.allow-bean-definition-overriding=true
security.jwt.secret-key=${SECURITY_KEY}



